In [8]:
import pandas as pd
import requests as r
import sqlalchemy
import time
import praw
import psaw
import datetime as dt
from psaw import PushshiftAPI

In [7]:
api=PushshiftAPI()
searchs = api.search_submissions(q="elon",
                            subreddit='cryptocurrency',
                            filter=['subreddit','author', 'title', 'subreddit','selftext',])

#for post in searchs:
    #posts.append([post.title, post.subreddit, post.url, post.selftext, post.author])
    #posts = pd.DataFrame(posts,columns=['title', 'subreddit', 'url', 'selftext', 'author'])

df = pd.DataFrame([submission.d_ for submission in searchs])
df

C:\Users\Argo\anaconda3\lib\site-packages\psaw\PushshiftAPI.py:192: UserWarning: Got non 200 code 429
  warnings.warn("Got non 200 code %s" % response.status_code)
C:\Users\Argo\anaconda3\lib\site-packages\psaw\PushshiftAPI.py:180: UserWarning: Unable to connect to pushshift.io. Retrying after backoff.
  warnings.warn("Unable to connect to pushshift.io. Retrying after backoff.")

,author,created_utc,selftext,subreddit,title,created
0,Revolutionary-Break2,1624716491,"Hi, guys I wanted to discuss a little bit abt ...",CryptoCurrency,Summer Season Coins,1.624734e+09
1,Trear,1624708956,"Hi, I am currently writing a paper about the I...",CryptoCurrency,Vulnerabilities of the IOTA Foundation,1.624727e+09
2,BrokenShield,1624708308,,CryptoCurrency,True Visionary Indeed - Long before Elon Musk ...,1.624726e+09
3,Abderrahmane456,1624694026,,CryptoCurrency,Dogecoin meme crypto Shiba Inu scores modest f...,1.624712e+09
4,riqelme,1624686585,,CryptoCurrency,Elon Musk agrees to speak with Twitter CEO Jac...,1.624705e+09
...,...,...,...,...,...,...
7223,CryptoCurrencyNews,1491051966,,CryptoCurrency,Elon Musk Announces Global SpaceX Private Flig...,1.491070e+09
7224,CryptoCurrencyNews,1489861055,,CryptoCurrency,Elon Musk’s SpaceX Is Seemingly Winning the Ra...,1.489879e+09
7225,twigwam,1488684158,,CryptoCurrency,Building the Hyperconnected Future on Blockcha...,1.488702e+09
7226,[deleted],1420511352,,CryptoCurrency,My Question to Elon Musk,1.420529e+09
7227,artur_oliver,1414428285,,CryptoCurrency,[video] Elon musk talks about virtual reality ...,1.414446e+09

In [6]:
api=PushshiftAPI()
searchs = api.search_submissions(q="musk",
                            subreddit='cryptocurrency',
                            filter=['subreddit','author', 'title', 'subreddit','selftext',])

#for post in searchs:
    #posts.append([post.title, post.subreddit, post.url, post.selftext, post.author])
    #posts = pd.DataFrame(posts,columns=['title', 'subreddit', 'url', 'selftext', 'author'])

dfmusk = pd.DataFrame([submission.d_ for submission in searchs])
dfmusk

C:\Users\Argo\anaconda3\lib\site-packages\psaw\PushshiftAPI.py:192: UserWarning: Got non 200 code 429
  warnings.warn("Got non 200 code %s" % response.status_code)
C:\Users\Argo\anaconda3\lib\site-packages\psaw\PushshiftAPI.py:180: UserWarning: Unable to connect to pushshift.io. Retrying after backoff.
  warnings.warn("Unable to connect to pushshift.io. Retrying after backoff.")

,author,created_utc,selftext,subreddit,title,created
0,Revolutionary-Break2,1624716491,"Hi, guys I wanted to discuss a little bit abt ...",CryptoCurrency,Summer Season Coins,1.624734e+09
1,Trear,1624708956,"Hi, I am currently writing a paper about the I...",CryptoCurrency,Vulnerabilities of the IOTA Foundation,1.624727e+09
2,BrokenShield,1624708308,,CryptoCurrency,True Visionary Indeed - Long before Elon Musk ...,1.624726e+09
3,Abderrahmane456,1624694026,,CryptoCurrency,Dogecoin meme crypto Shiba Inu scores modest f...,1.624712e+09
4,riqelme,1624686585,,CryptoCurrency,Elon Musk agrees to speak with Twitter CEO Jac...,1.624705e+09
...,...,...,...,...,...,...
4818,TheWizardCovfefe,1497066158,,CryptoCurrency,"Nikola Tesla, Elon Musk, Scott Bakula and Dean...",1.497084e+09
4819,CryptoCurrencyNews,1491051966,,CryptoCurrency,Elon Musk Announces Global SpaceX Private Flig...,1.491070e+09
4820,twigwam,1488684158,,CryptoCurrency,Building the Hyperconnected Future on Blockcha...,1.488702e+09
4821,[deleted],1420511352,,CryptoCurrency,My Question to Elon Musk,1.420529e+09
4822,artur_oliver,1414428285,,CryptoCurrency,[video] Elon musk talks about virtual reality ...,1.414446e+09

In [9]:
#concanate then dedupe 
elondf=pd.concat([df,dfmusk])
elondf.count()

author         12051
created_utc    12051
selftext       11985
subreddit      12051
title          12051
created        12051
dtype: int64

In [10]:
eloncount=elondf.groupby(["author","created_utc"]).count()
eloncount[eloncount["selftext"]>1]

                                  selftext  subreddit  title  created
author               created_utc
-Everythinginbalance 1624357620          2          2      2        2
-Just_Another_Guy-   1612146929          2          2      2        2
                     1612802066          2          2      2        2
-Multivitamina-      1578604987          2          2      2        2
-OnBorrowedTime-     1623037000          2          2      2        2
...                                    ...        ...    ...      ...
zombieintraining     1622897066          2          2      2        2
zuperfly             1621169170          2          2      2        2
zymkc                1620635937          2          2      2        2
zymwise              1597577488          2          2      2        2
zzaann               1612464890          2          2      2        2

[4119 rows x 4 columns]

In [11]:
elondf1= elondf.drop_duplicates()

In [14]:
elondf1["title"]

0                                     Summer Season Coins
1                  Vulnerabilities of the IOTA Foundation
2       True Visionary Indeed - Long before Elon Musk ...
3       Dogecoin meme crypto Shiba Inu scores modest f...
4       Elon Musk agrees to speak with Twitter CEO Jac...
                              ...
4783    Musk has finally announced the payload for the...
4784    My tweet to Eleon Musk about Cryptocurrencies ...
4806                  Review my homework on MCO please :)
4815    [Discussion]Are idiots the only ones getting o...
4816    Musk, Zuckerberg &amp; Hawaii Calls For Univer...
Name: title, Length: 7909, dtype: object

In [3]:
df["time"]=pd.to_datetime(df["created_utc"].apply(float),unit="s")

In [4]:
df1= df.resample("1D",on="time").count()

In [5]:
df2= df1.loc["2021-1-1":"2021-5-30",["title"]]
df2

            title
time
2021-01-01      0
2021-01-02      3
2021-01-03      3
2021-01-04      0
2021-01-05      2
...           ...
2021-05-26     39
2021-05-27     21
2021-05-28     29
2021-05-29     22
2021-05-30     32

[150 rows x 1 columns]

In [16]:
elondf1.to_csv("redditElonMusk.csv", index=True)